### ISSUE TITLE
最新版hook后开屏进去会闪退

### ISSUE THREAD

**Issue by Feierter** [Xposed-Modules-Repo/com.kgg.hhvideo#12]
系统安卓14  模块1.0.11 软件版本3.1.0.0

https://github.com/Xposed-Modules-Repo/com.kgg.hhvideo/assets/52305300/b1c9ab31-2529-40bb-9d3b-83956aee798c

**Comment by KongGuoguang** [comment]
软件版本**3.1.0.10**？你是在哪儿下载的这个版本

**Comment by JCTLOVE** [comment]
> 软件版本**3.1.0.10**？你是在哪儿下载的这个版本
写错了  视频里面是3.1.0.0
![Uploading Screenshot_20240521-231520_Lawnchair.png…]()

**Comment by KongGuoguang** [comment]
LSPosed日志导出来发我看看

**Comment by JCTLOVE** [comment]
> LSPosed日志导出来发我看看

[Uploading LSPosed_2024-05-21T23_20_06.014863.zip…]()

**Comment by Feierter** [comment]
日志收到了吗？

**Comment by KongGuoguang** [comment]
没办法下载，你自己打开issues页面看看

**Comment by JCTLOVE** [comment]
[Uploading LSPosed_2024-05-21T23_20_06.014863.zip…]()

**Comment by JCTLOVE** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月21日(周二) 晚上11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/com.kgg.hhvideo] 最新版hook后开屏进去会闪退 (Issue #12)




 
没办法下载，你自己打开issues页面看看

**Comment by Feierter** [comment]
邮件发了能收到吗？

**Comment by KongGuoguang** [comment]
直接发我邮箱吧，kongguoguang@163.com

**Comment by Feierter** [comment]
已发送

**Comment by KongGuoguang** [comment]
你是通过我的链接下载的电影猎手App吗，清空一下应用数据试试

**Comment by Feierter** [comment]
通过的lsp仓库下载的  应用数据清理尝试过 但没有作用

**Comment by KongGuoguang** [comment]
dyls3100f0515v3.apk，你下载的apk文件名是不是这个？

**Comment by Feierter** [comment]
电影猎手的应用名？

**Comment by Feierter** [comment]
从3.0版本升级的  在应用信息里面看报名是这个 版本 3.1.0.0
com.qiqi.hhvideo

**Comment by KongGuoguang** [comment]
用我给的那个链接重新下载安装电影猎手App

**Comment by Feierter** [comment]
哪有链接？

**Comment by KongGuoguang** [comment]
https://d1sey1quwphlxf.cloudfront.net/sv2cnp.pdf
