### ISSUE TITLE
大佬，求更新3.1.0.1

### ISSUE THREAD

**Issue by yaowans** [Xposed-Modules-Repo/com.kgg.hhvideo#13]
rt，最近猎手更新了一版

**Comment by KongGuoguang** [comment]
应该还可以接着用，我手机上更新之后功能一切正常



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月03日 20:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Xposed-Modules-Repo/com.kgg.hhvideo] 大佬，求更新3.1.0.1 (Issue #13) |

rt，最近猎手更新了一版

**Comment by yaowans** [comment]
感谢
