### ISSUE TITLE
大佬求更新3.1.0.3  旧模块会提示服务器不可用

### ISSUE THREAD

**Issue by Feierter** [Xposed-Modules-Repo/com.kgg.hhvideo#14]
![微信图片_20240721214856](https://github.com/user-attachments/assets/34211867-b7ac-4d1e-9590-dd82c13a1cb0)

**Comment by Feierter** [comment]
![微信图片_20240721215004](https://github.com/user-attachments/assets/5b094a81-9f55-4379-a033-f747cb19ed87)

**Comment by KongGuoguang** [comment]
已更新

**Comment by Feierter** [comment]
666 感谢

**Comment by JCTLOVE** [comment]
大佬 哪里更新在哪呢 找不到(⁎⚈᷀᷁ᴗ⚈᷀᷁⁎)

**Comment by KongGuoguang** [comment]
去GitHub release页面下载，LSPosed仓库还没同步到



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月21日 22:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Xposed-Modules-Repo/com.kgg.hhvideo] 大佬求更新3.1.0.3  旧模块会提示服务器不可用 (Issue #14) |

大佬 哪里更新在哪呢 找不到(⁎⚈᷀᷁ᴗ⚈᷀᷁⁎)
