### ISSUE TITLE
请问作者还更新吗？

### ISSUE THREAD

**Issue by RockHT** [Xposed-Modules-Repo/com.kgg.hhvideo#7]

**Comment by KongGuoguang** [comment]
555电影App也没更新吧，我看最新还是v3.0.9.1版本

**Comment by RockHT** [comment]
> 555电影App也没更新吧，我看最新还是v3.0.9.1版本

作者大大你好，模块正常运行，但是开屏广告和视频下方的广告屏蔽失效了

**Comment by KongGuoguang** [comment]
已更新，请下载使用

**Comment by RockHT** [comment]
> 已更新，请下载使用

好的，谢谢大佬

**Comment by RockHT** [comment]
大佬，555电影更新成电影猎手了，花里胡哨的，感觉不好用了，请问后续还有必要继续做模块吗？
